# Generated by Django 4.1.5 on 2023-02-05 17:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('organisation', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('degree', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('field_of_study', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('title', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CvContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('summary', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma separated list of skills', max_length=500)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='cv.certificate')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cv.education')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='cv.workexperience')),
            ],
        ),
    ]
